---
- napalm_get_facts:
    hostname={{ inventory_hostname }}
    username={{ ansible_user }}
    password={{ ansible_ssh_pass }}
    dev_os=ios
    filter='bgp_neighbors,facts,interfaces,interfaces_counters,arp_table,lldp_neighbors,mac_address_table'

