- name: generic read/report
  hosts: all
  vars:
  - results: "{{inventory_dir}}/results"
  tasks:
  - include: "tasks/read-{{src|default('cisco-ios-facts')}}.yml"
  - include: "report-{{dst|default('template')}}.yml"
