#
# Generate "create report from a template" module
#
# Variables
#   results - output directory
#   fmt     - desired format
#   dest    - destination file name
#   report  - report type 
---
- set_fact: report_template_src_file="templates/{{report}}-{{fmt}}.j2"
  when: report is defined and fmt is defined
- template:
    src:  "{{report_template_src_file|default('uptime-text.j2')}}"
    dest: "{{results}}/{{output|default('output.log')}}"
  vars:
    allhosts: "{{hostvars}}"
  run_once: true
