---
- hosts: ios
  connection: local
  gather_facts: false
  tasks:
  - ios_command:
       commands: 
         - show run
    register: output
  - copy:
      content: "{{ output.stdout[0] }}"
      dest: "./{{ inventory_hostname }}.configs" 
